[package]
name = "example_poseidon"
type = "bin"
authors = ["TACEO GmbH"]
compiler_version = ">=0.36.0"

[dependencies]
poseidon = { tag = "v0.2.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon" }
