[package]
name = "example_poseidon"
type = "bin"
authors = ["TACEO GmbH"]
compiler_version = ">=0.19.2"

[dependencies]
poseidon = { tag = "v0.1.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon" }
