date := `date +%Y-%m-%d`

default: collect-circuit-sizes

collect-circuit-sizes outfile=('stats-' + date + '.md'):
  rm {{outfile}} 2> /dev/null || true
  echo "# Circuit Sizes for Examples" >> {{outfile}}
  
  echo "## Circuit Sizes" >> {{outfile}}
  echo "\`\`\`" >> {{outfile}}
  nargo info --workspace >> {{outfile}}
  echo "\`\`\`" >> {{outfile}}

  echo "## Noir Versions" >> {{outfile}}
  echo "\`\`\`" >> {{outfile}}
  nargo --version >> {{outfile}}
  echo "\`\`\`" >> {{outfile}}

  echo "## Crate Versions" >> {{outfile}}
  echo "\`\`\`" >> {{outfile}}
  bash -c "grep -h tag ../*/Nargo.toml" >> {{outfile}}
  echo "\`\`\`" >> {{outfile}}
